<a href="https://colab.research.google.com/github/CristinaMflores/BigData/blob/main/Aula04_25102024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

Criação de um Array a partir de uma lista:

In [ ]:
lista1=[1,2,3,4,5,6]
array1=np.array(lista1)
print(array1)

[1 2 3 4 5 6]
Principais Funções para Definição de Arrays partindo do Zero:

In [ ]:
print(array1.dtype)

int64

In [ ]:
print(array1.shape)

(6,)

In [ ]:
zeros=np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
number_one=np.ones((4,3))
print(number_one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
vazio=np.empty((4,4))
print(vazio)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.11261162e-306]
 [9.34598925e-307 1.42419802e-306 8.01092457e-307 6.23053614e-307]
 [1.86919649e-306 1.78020848e-306 1.11258175e-306 1.78019082e-306]
 [1.33511290e-306 4.67296747e-307 7.23188049e-308 1.35994435e-317]]

In [ ]:
sequencia=np.arange(-100,-10,10)
print(sequencia)

[-100  -90  -80  -70  -60  -50  -40  -30  -20]

In [ ]:
aleatorio=np.random.rand(2,3)
print(aleatorio)

[[0.20359756 0.4669691  0.9314291 ]
 [0.75979036 0.0328074  0.53263958]]
Funções para Manipulação de Arrays Existentes:

In [ ]:
array2=array1.reshape((3,2))
print(array2)

[[1 2]
 [3 4]
 [5 6]]

In [ ]:
quebra=np.split(array2,3)
print(quebra)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

In [ ]:
array3=np.array([1,2])
array4=np.array([3,4])
print(array3,array4)
uniao=np.concatenate((array3,array4))
print(uniao)

[1 2] [3 4]
[1 2 3 4]
Operações com Séries Pandas:

Criação:

In [ ]:
serie1=pd.Series([10,20,30],index=['a','b','c'])
print(serie1)

a    10
b    20
c    30
dtype: int64
Seleção por Índice:

In [ ]:
print(serie1['a'])
print('--------')
print(serie1[['a']])
print('--------')
print(serie1[['a','c']])

10
--------
a    10
dtype: int64
--------
a    10
c    30
dtype: int64
Operações de Filtragem e Aritméticas:


In [ ]:
filtro1=serie1[serie1>15]
print(filtro1)
print('--------')
serie2=serie1*3
print(serie2)

b    20
c    30
dtype: int64
--------
a    30
b    60
c    90
dtype: int64

In [ ]:
serie3=pd.Series([1,2,3,4])
serie4=pd.Series([5,6,7,8])

#Operações Fundamentais:
print(serie3+serie4)
print('--------')
print(serie3-serie4)
print('--------')
print(serie3*serie4)
print('--------')
print(serie3/serie4)

0     6
1     8
2    10
3    12
dtype: int64
--------
0   -4
1   -4
2   -4
3   -4
dtype: int64
--------
0     5
1    12
2    21
3    32
dtype: int64
--------
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64

In [ ]:
#Suporte a Valores Nulos:

serievazia=pd.Series([10,np.nan,30])
print(serievazia) #NaN = 'Null as Number'

0    10.0
1     NaN
2    30.0
dtype: float64

In [ ]:
print(serie3+serievazia)
print('--------')
print(serie3-serievazia)
print('--------')
print(serie3*serievazia)
print('--------')
print(serie3/serievazia)

0    11.0
1     NaN
2    33.0
3     NaN
dtype: float64
--------
0    -9.0
1     NaN
2   -27.0
3     NaN
dtype: float64
--------
0    10.0
1     NaN
2    90.0
3     NaN
dtype: float64
--------
0    0.1
1    NaN
2    0.1
3    NaN
dtype: float64